# ESLint v5.15.2
parserOptions:
  ecmaVersion: 10
  ecmaFeatures:
    impliedStrict: true
  sourceType: module
env:
  browser: true
  es6:     true
  jasmine: true
  node:    true
rules:
  id-blacklist:
  - error
  no-restricted-globals:
  - error
  no-restricted-imports:
  - error
  no-restricted-modules:
  - error
  no-restricted-syntax:
  - error
  accessor-pairs: warn
  array-bracket-newline: warn
  array-bracket-spacing:
  - error
  - never
  - singleValue: false
    objectsInArrays: false
    arraysInArrays: false
  array-callback-return: warn
  array-element-newline: 'off'
  arrow-body-style:
  - warn
  - as-needed
  arrow-parens:
  - error
  - as-needed
  arrow-spacing:
  - error
  - before: true
    after: true
  block-scoped-var: warn
  block-spacing:
  - error
  - always
  brace-style:
  - warn
  - 1tbs
  - allowSingleLine: true
  callback-return: warn
  camelcase:
  - warn
  - properties: always
  capitalized-comments: 'off'
  class-methods-use-this: warn
  comma-dangle:
  - error
  - always-multiline
  comma-spacing:
  - error
  - before: false
    after: true
  comma-style:
  - error
  - last
  complexity: 'off'
  computed-property-spacing:
  - error
  - never
  consistent-return: 'off'
  consistent-this: 'off'
  constructor-super: error
  curly:
  - error
  - multi-line
  - consistent
  default-case: error
  dot-location:
  - error
  - property
  dot-notation:
  - error
  - allowKeywords: true
  eqeqeq:
  - warn
  - always
  eol-last: error
  for-direction: error
  func-call-spacing:
  - error
  - never
  func-name-matching:
  - error
  - always
  func-names:
  - warn
  - as-needed
  func-style:
  - off
  function-paren-newline:
  - error
  - multiline
  generator-star-spacing:
  - error
  - before: false
    after: true
  getter-return:
  - error
  - allowImplicit: true
  global-require: warn
  guard-for-in: warn
  handle-callback-err: error
  id-length: 'off'
  id-match: 'off'
  implicit-arrow-linebreak:
  - error
  - beside
  indent:
  - error
  - 2
  - SwitchCase: 1
    MemberExpression: 'off'
  init-declarations:
  - 'off'
  key-spacing:
  - error
  - beforeColon: false
    afterColon:  true
    mode:        minimum
    align:       value
  keyword-spacing:
  - error
  - before: true
    after: true
  line-comment-position: 'off'
  linebreak-style:
  - 'off'
  lines-around-comment:
  - warn
  - beforeBlockComment: true
    afterBlockComment: false
    beforeLineComment: false
    afterLineComment: false
    allowBlockStart: true
    allowBlockEnd: false
    allowObjectStart: false
    allowObjectEnd: false
    allowArrayStart: false
    allowArrayEnd: false
  lines-between-class-members:
  - warn
  - always
  - exceptAfterSingleLine: true
  max-classes-per-file:
  - warn
  - 2
  max-depth: warn
  max-len:
  - warn
  - code: 120
    ignoreComments: true
    ignoreStrings: true
    ignoreTemplateLiterals: true
    ignoreUrls: true
  max-lines: 'off'
  max-lines-per-function: off
  max-nested-callbacks:
  - warn
  - 2
  max-params:
  - warn
  - 4
  max-statements:
  - warn
  - 20
  max-statements-per-line:
  - warn
  - max: 2
  multiline-comment-style: 'off'
  multiline-ternary: 'off'
  new-cap:
  - warn
  - newIsCap: true
    capIsNew: true
    properties: true
  new-parens: 'off'
  newline-per-chained-call:
  - warn
  - ignoreChainWithDepth: 3
  no-alert: warn
  no-array-constructor: warn
  no-async-promise-executor: error
  no-await-in-loop: error
  no-bitwise: warn
  no-buffer-constructor: error
  no-caller: error
  no-case-declarations: error
  no-catch-shadow: error
  no-class-assign: error
  no-compare-neg-zero: error
  no-cond-assign:
  - error
  - except-parens
  no-confusing-arrow:
  - error
  - allowParens: true
  no-console:
  - warn
  - allow:
    - error
    - info
    - time
    - timeEnd
    - warn
  no-const-assign: error
  no-constant-condition:
  - error
  - checkLoops: true
  no-continue: warn
  no-control-regex: warn
  no-delete-var: error
  no-div-regex: off
  no-debugger: error
  no-dupe-args: error
  no-dupe-class-members: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-duplicate-imports:
  - error
  - includeExports: true
  no-else-return: error
  no-empty:
  - error
  - allowEmptyCatch: false
  no-empty-character-class: error
  no-empty-function: error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-ex-assign: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-boolean-cast: error
  no-extra-label: warn
  no-extra-parens:
  - warn
  - all
  - nestedBinaryExpressions: false
    enforceForArrowConditionals: false
  no-extra-semi: error
  no-fallthrough:
  - error
  - commentPattern: fallthrough
  no-floating-decimal: error
  no-func-assign: error
  no-global-assign: error
  no-implicit-coercion: warn
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: 'off'
  no-inner-declarations:
  - error
  - functions
  no-invalid-regexp: error
  no-invalid-this: warn
  no-irregular-whitespace:
  - warn
  - skipStrings: false
    skipRegExps: false
    skipComments: true
    skipTemplates: false
  no-iterator: error
  no-label-var: error
  no-labels: 'off'
  no-lone-blocks: error
  no-lonely-if: warn
  no-loop-func: error
  no-magic-numbers:
  - warn
  - ignoreArrayIndexes: true
    ignore:
    - -1
    - 0
    - 1
    - 2
    - 3
    - 10
    - 60
    - 200
    - 201
    - 204
    - 207
    - 302
    - 304
    - 400
    - 401
    - 403
    - 404
    - 405
    - 408
    - 409
    - 410
    - 412
    - 413
    - 422
    - 429
    - 449
    - 500
    - 503
    - 1000
    - 3000
  no-misleading-character-class: error
  no-mixed-operators:
  - warn
  - allowSamePrecedence: true
  no-mixed-requires:
  - error
  - allowCall: true
  no-mixed-spaces-and-tabs: error
  no-multi-assign: warn
  no-multi-spaces:
  - error
  - ignoreEOLComments: true
    exceptions:
      AssignmentExpression: true
      IfStatement: true
      ImportDeclaration: true
      ImportSpecifier: true
      VariableDeclarator: true
  no-multi-str: error
  no-multiple-empty-lines:
  - warn
  - max: 2
  no-negated-condition: warn
  no-nested-ternary: warn
  no-new: warn
  no-new-func: error
  no-new-object: warn
  no-new-require: error
  no-new-symbol: error
  no-new-wrappers: warn
  no-obj-calls: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign:
  - error
  - props: true
  no-path-concat: error
  no-plusplus: 'off'
  no-process-env: 'off'
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: 'off'
  no-redeclare: error
  no-regex-spaces: error
  no-return-assign:
  - error
  - always
  no-return-await: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-shadow:
  - warn
  - builtinGlobals: true
    hoist: all
    allow:
    - err
    - event
    - resolve
    - reject
  no-shadow-restricted-names: error
  no-sparse-arrays: warn
  no-sync: error
  no-tabs: warn
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-this-before-super: error
  no-throw-literal: error
  no-trailing-spaces:
  - error
  - skipBlankLines: false
  no-undef:
  - error
  - typeof: true
  no-undef-init: error
  no-undefined: warn
  no-underscore-dangle:
  - warn
  - allow:
    - _ts
    - _etag
  no-unexpected-multiline: error
  no-unmodified-loop-condition: warn
  no-unneeded-ternary:
  - error
  - defaultAssignment: false
  no-unreachable: error
  no-unsafe-finally: warn
  no-unsafe-negation: error
  no-unused-expressions: error
  no-unused-labels: error
  no-unused-vars: error
  no-use-before-define:
    - warn
    - classes: false
      functions: false
  no-useless-call: error
  no-useless-catch: error
  no-useless-concat: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename: error
  no-useless-return: error
  no-var: warn
  no-void: off
  no-warning-comments: warn
  no-whitespace-before-property: error
  no-with: warn
  nonblock-statement-body-position:
  - error
  - beside
  object-curly-newline:
  - warn
  - ObjectExpression:
      consistent: true
      minProperties: 4
    ObjectPattern:
      multiline: true
  object-curly-spacing:
  - error
  - always
  - objectsInObjects: true
    arraysInObjects: true
  object-property-newline:
  - warn
  - allowMultiplePropertiesPerLine: true
  object-shorthand:
  - warn
  - always
  one-var:
  - error
  - never
  one-var-declaration-per-line: 'off'
  operator-assignment:
  - error
  - always
  operator-linebreak:
  - error
  - before
  - overrides:
      "?": ignore
      ":": ignore
  padded-blocks: 'off'
  padding-line-between-statements: 'off'
  prefer-arrow-callback:
  - error
  - allowNamedFunctions: true
    allowUnboundThis: true
  prefer-const:
  - error
  - destructuring: any
    ignoreReadBeforeAssign: false
  prefer-destructuring:
  - warn
  - array: false
    object: true
  - enforceForRenamedProperties: false
  prefer-named-capture-group: warn
  prefer-numeric-literals: warn
  prefer-object-spread: off
  prefer-promise-reject-errors:
  - warn
  - allowEmptyReject: true
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: warn
  quote-props:
  - error
  - as-needed
  - keywords: false
    unnecessary: true
  quotes:
  - error
  - single
  - avoidEscape: true
    allowTemplateLiterals: true
  radix:
  - error
  - always
  require-atomic-updates: error
  require-await: error
  require-unicode-regexp: error
  require-yield: error
  rest-spread-spacing:
  - error
  - never
  semi:
  - error
  - always
  semi-spacing:
  - error
  - before: false
    after: true
  semi-style:
  - error
  - last
  sort-imports:
  - warn
  - ignoreCase: true
    memberSyntaxSortOrder:
    - none
    - all
    - single
    - multiple
  sort-keys:
  - warn
  - asc
  - caseSensitive: false
    natural: true
  sort-vars:
  - warn
  - ignoreCase: true
  space-before-blocks:
  - error
  - always
  space-before-function-paren:
  - error
  - anonymous: never
    named: never
  space-in-parens:
  - error
  - never
  space-infix-ops: error
  space-unary-ops:
  - error
  - words: true
    nonwords: false
  spaced-comment:
  - error
  - always
  - markers:
    - "*"
  switch-colon-spacing:
  - error
  - after: true
    before: false
  symbol-description: error
  template-curly-spacing:
  - warn
  - never
  template-tag-spacing:
  - error
  - never
  unicode-bom:
  - error
  - never
  use-isnan: error
  valid-typeof: error
  vars-on-top: warn
  wrap-iife:
  - off
  - outside
  wrap-regex: 'off'
  yield-star-spacing:
  - error
  - after
  yoda:
  - error
  - never
  - onlyEquality: true
