extends:
  - '@digitallinguistics/eslint-config'

env:
  mocha: true
  shared-node-browser: true

globals:
  process: true

overrides:
  - files:
      - '**/*.test.*'
    rules:
      func-names:            off
      prefer-arrow-callback: off
      max-nested-callbacks:  off
      max-params:            off
      no-invalid-this:       off
      no-magic-numbers:      off
      no-param-reassign:     off
      no-unused-expressions: off