module.exports = {
  Abbreviation: require('./Abbreviation'),
  Access: require('./Access'),
  Address: require('./Address'),
  Annotation: require('./Annotation'),
  Bundle: require('./Bundle'),
  GeoJSON: require('./GeoJSON'),
  Language: require('./Language'),
  Lexeme: require('./Lexeme'),
  LexemeReference: require('./LexemeReference'),
  Lexicon: require('./Lexicon'),
  Location: require('./Location'),
  Media: require('./Media'),
  Morpheme: require('./Morpheme'),
  MultiLangString: require('./MultiLangString'),
  Note: require('./Note'),
  Orthography: require('./Orthography'),
  Person: require('./Person'),
  Phoneme: require('./Phoneme'),
  Reference: require('./Reference'),
  Sentence: require('./Sentence'),
  Tags: require('./Tags'),
  Text: require('./Text'),
  Transcription: require('./Transcription'),
  Translation: require('./Translation'),
  URL: require('./URL'),
  Word: require('./Word'),
};