module.exports = {
  Abbreviation: require('./Abbreviation'),
  Access: require('./Access'),
  Address: require('./Address'),
  Annotation: require('./Annotation'),
  BibliographicReference: require('./BibliographicReference'),
  Bundle: require('./Bundle'),
  DatabaseReference: require('./DatabaseReference'),
  Language: require('./Language'),
  Lexeme: require('./Lexeme'),
  Location: require('./Location'),
  Media: require('./Media'),
  Morpheme: require('./Morpheme'),
  MultiLangString: require('./MultiLangString'),
  Note: require('./Note'),
  Orthography: require('./Orthography'),
  Person: require('./Person'),
  Phoneme: require('./Phoneme'),
  Tags: require('./Tags'),
  Text: require('./Text'),
  Transcription: require('./Transcription'),
  Translation: require('./Translation'),
  Utterance: require('./Utterance'),
  Word: require('./Word'),
};