module.exports = {
  abbreviation: require('./abbreviation'),
  access: require('./access'),
  address: require('./address'),
  bundle: require('./bundle'),
  contributor: require('./contributor'),
  dateCreated: require('./dateCreated'),
  dateModified: require('./dateModified'),
  dateRecorded: require('./dateRecorded'),
  language: require('./language'),
  lexeme: require('./lexeme'),
  lexemeReference: require('./lexemeReference'),
  lexicon: require('./lexicon'),
  location: require('./location'),
  media: require('./media'),
  multiLangString: require('./multiLangString'),
  note: require('./note'),
  orthography: require('./orthography'),
  person: require('./person'),
  phoneme: require('./phoneme'),
  phrase: require('./phrase'),
  reference: require('./reference'),
  tags: require('./tags'),
  text: require('./text'),
  url: require('./url'),
  word: require('./word'),
};
