module.exports = {
  // Abbreviation:    require('./Abbreviation'),
  Access:          require('./Access'),
  Address:         require('./Address'),
  Bundle:          require('./Bundle'),
  Contributor:     require('./Contributor'),
  DateCreated:     require('./DateCreated'),
  DateModified:    require('./DateModified'),
  DateRecorded:    require('./DateRecorded'),
  Language:        require('./Language'),
  Lexeme:          require('./Lexeme'),
  LexemeReference: require('./LexemeReference'),
  Lexicon:         require('./Lexicon'),
  Location:        require('./Location'),
  Media:           require('./Media'),
  MultiLangString: require('./MultiLangString'),
  Note:            require('./Note'),
  Orthography:     require('./Orthography'),
  Person:          require('./Person'),
  Phoneme:         require('./Phoneme'),
  Phrase:          require('./Phrase'),
  Reference:       require('./Reference'),
  Tags:            require('./Tags'),
  Text:            require('./Text'),
  Url:             require('./Url'),
  Word:            require('./Word'),
};
