module.exports = {
  Abbreviation:    require('./abbreviation'),
  Access:          require('./access'),
  Address:         require('./address'),
  Bundle:          require('./bundle'),
  Contributor:     require('./contributor'),
  DateCreated:     require('./dateCreated'),
  DateModified:    require('./dateModified'),
  DateRecorded:    require('./dateRecorded'),
  Language:        require('./language'),
  Lexeme:          require('./lexeme'),
  LexemeReference: require('./lexemeReference'),
  Lexicon:         require('./lexicon'),
  Location:        require('./location'),
  Media:           require('./media'),
  MultiLangString: require('./multiLangString'),
  Note:            require('./note'),
  Orthography:     require('./orthography'),
  Person:          require('./person'),
  Phoneme:         require('./phoneme'),
  Phrase:          require('./phrase'),
  Reference:       require('./reference'),
  Tags:            require('./tags'),
  Text:            require('./text'),
  Url:             require('./url'),
  Word:            require('./word'),
};
