name: release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: install dependencies
        run:  npm ci

      - name: build
        run:  npm run build

      - name: run tests
        run:  npm test

      - name: publish to DLx CDN
        run:  npm run upload
        env:
          AZURE_CONNECTION_STRING: ${{secrets.AZURE_CONNECTION_STRING}}

      - name: publish to npm
        run:  npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: publish to GitHub Packages
        run:  npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: create docs
        run:  npm run docs

      - name: publish GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:  ./docs
