name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '26 17 * * Tue' # every Tuesday @ 5:27 p.m.
  workflow_dispatch:

jobs:

  run-tests:
    name:    run tests
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: cache Node.js modules
        id:   cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run:  npm ci

      - name: build library
        run:  npm run build

      - name: run tests
        run:  npm test