name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: install Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: install package
        run:  npm ci

      - name: build
        run:  npm run build

      - name: test
        run:  npm test
